version: 2.1

executors:
  build:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<< parameters.go-version >>
    working_directory: /go/src/github.com/alyosha/slack-utils

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  build:
    parameters:
      go-version:
        type: string
      golangci-lint-version:
        type: string

    executor:
      name: build
      go-version: << parameters.go-version >>

    steps:
      - checkout

      - go_mod_download

      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v<< parameters.golangci-lint-version >>

      - run:
          name: Run golangci-lint
          command: ./bin/golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck
      - run:
          name: Run tests
          command: go test -race -v ./...

workflows:
  golang-workflow:
    jobs:
      - build:
          go-version: "1.14"
          golangci-lint-version: "1.16.0"
